### ISSUE TITLE
请教多行匹配的使用

### ISSUE THREAD

**Issue by tomcatzh** [crapex/pymud#2]
很小的一个问题，请教一下，尝试加入QQ群，似乎没有通过

我尝试多行匹配
        self.tri_test = Trigger(self.session, id = 'tri_test', patterns = (
                                                            #r'^当铺 -.*$',
                                                            r'^\s*南大街-+当铺-+库房\s*$',
                                                            r'^\s*荣宝斋\s*$',
                                                            #r'^\s*([\w ]+?)\(([\w ]+?)\)\s*$',
                                                    ), group = "test", onSuccess = self.ontri_test)

我确信每个pattern单独都是可以匹配的，但是不知道为何多行匹配不成功。

我阅读了一下多行匹配的代码，似乎又个bug，就是如果我在这里加了一个逗号（会被判断为多行），但实际只有一行的情况，就会匹配不上。但我尝试做了多行似乎也匹配不到，请加一下大大我这里是不是有什么理解问题

这个是扬州当铺的文字

│当铺 -  ★                                                                                                                                                                                     |                              │
│                            拍卖行                                                                                                                                                            |                              │
│                              ｜                                                                                                                                                              |                              │
│                  南大街-----当铺-----库房                                                                                                                                                    |                              │
│                              ｜                                                                                                                                                              |                              │
│                            荣宝斋                                                                                                                                                            |                              │
│    这是一家以买卖公平著称的夏日当铺，一个五尺高的柜台挡在你的面前，柜台上摆着个牌子(paizi)                                                                                                   |                              │
│，柜台后坐着唐老板，一双精明的眼睛上上下下打量着你，太阳充足的阳光照在他的脸上，令他的微笑                                                                                                    |                              │
│更加温暖。

**Comment by crapex** [comment]
Trigger里的多行匹配，必须是连续的行，你在例子中的当铺里，南大街-当铺与荣宝斋中间有内容为||的行。

**Comment by crapex** [comment]
问题已解决（多行匹配的连续行问题）。
