### ISSUE TITLE
你好大神，可以加个运行日志吗

### ISSUE THREAD

**Issue by zb4608656** [crapex/pymud#7]
你好大神，在运行的时候有些报错，如果可以加个日志的话，能更方便调试，谢谢~

**Comment by crapex** [comment]
带日志版本，0.20.0a1 PRE-RELEASE已发布，可以使用
pip install --upgrade pymud==0.20.0a1
进行安装尝鲜。
具体日志使用，请在app中使用#help log查看
一些示例：
#log start: 在本会话中启动日志记录
#log start -r: 在本会话中以ANSI方式启动日志记录
#log stop: 停止默认日志
#log show: 弹出日志查看选择框

**Comment by crapex** [comment]
0.20.0正式版已发布，带日志功能。详情查看
https://pymud.readthedocs.io
